Vagrant.configure("2") do |config|

  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/trusty64"
    web.vm.hostname = "webserver.test"
    web.vm.network :private_network, ip: "<ip>"
    web.vm.provision "shell", inline: <<-SHELL
      apt-get update -y
      apt-get install apache2 -y
    SHELL
  end 
  

  config.vm.define "db" do |db|
    db.vm.box = "centos/7"
    db.vm.hostname = "database.test"
    db.vm.network :private_network, ip: "<ip>"
    db.vm.provision "shell", inline: <<-SHELL
      yum update -y
      yum install sqlite -y 
    SHELL
  end
end
